services:
  - docker

jobs:
  include:
  - stage: build docker image
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t wmuengineer/sinatra .
    - docker images
    - docker tag wmuengineer/sinatra $DOCKER_USERNAME/sinatra
    - docker push $DOCKER_USERNAME/sinatra
  - stage: test
    script: docker run --rm $DOCKER_USERNAME/sinatra /bin/sh -c "cd /root/sinatra;
      bundle exec rake test"
  - script: docker run --rm $DOCKER_USERNAME/sinatra /bin/sh -c "cd /root/sinatra;
      bundle exec rake test"

env:
  global:
    - secure: SVV8w34LHZ3hDAVgoXLU4SW5IFasC+ySyzZt3OoyfWBmc9dMgZWKnY4oz8kVCDS+J/xErgvNlF1X9S9K98tB3ARLYpb0YzR/sHEkaowbn9RnOGXKye3X45IAizz+YvhjE1yaSX+jsaYC3GqCfMMNtDgXvxsExpalj1z2PO8O7+KIh8zwDuh90517a/muodQi75n5ZTaNcQQJ3a9Wfnms+bVvgUoHOl4TaKe/mlhUh/cJATiGDWt6boZ72HePzEswS26cldMhMH27QbSN5S4MvsmBKmDDKO3ANIEAwgjzP70KYhPGfsu+5fO55oB7eYym+rvhUKrc3+ioWhuwmak2O8vztio11NkDJoN5qk9W4nEyXkyDyPXmbJ/e4VXFkczxApZHGMGoQj8s0qiS1pNV8BzfIXpXRQZZFMmzuqqXm8E9QAtkFJ/XYHN/Y8rv2ROd8u5sPPUtftYmKMju2AwKC/klcq0mp40azkyKo0shHIwlSbAR5JkAzTCKyQ0G0EdFa89Jt/wr3VoKNVKDeEhEu5/zrxNAQUznprcQClGYeWBiZsrLGWYyv54lb35UAJ1kYgkZBPkGzRhgebavSPSJcCEGargEUQQjyVKjhUYkMctsXoXL3y+3bRIGxdIIe1hAe37ErsL6E8w5QFG2nSDUJE255BdhN0hp8UuaNqba32Y=
    - secure: VOENpe40rr/L7KKVTfgChnCU4X/Asst5UztBj2VgsFQMDI5vI+/R6mvKVR6qd83MTAuB7fEL9jiVLNIjMYOVJ2KPOQXcan106bPeYuKWVWT/dEqi+J43bludHYBWkFi1qg0S3xElNCJs3rnC56pdZ/WYmI/vmW9q3ruYkMIZ+x8wqdsuQzx0gnQQYxvsXJwG/EbYJOaXs/gwEltnaASX2NS/wcJ9nXI1RR0scJGSLc7bL5RRTQt9dWTy9Wx4AvHmSoe8rAHZmXHr3H/sMWWYMY4KqQWo9j9G0qrQ4R5mnUJ1gZJQv2gQMq0wmwCAwKwNtAD9y8XcMTEJ8ERWP0T8H2EFLRpSX1xJ8wAhhlq60MOO+PUlkNut8TS/RHqUH2uRdR12zyA0b7FXTXoXo3nTcqBG0JiQ4ApQa+y8N9HoDij/KHvRr2JckZTcG5ftz1PpoiUbwuSMjId5JcnzYXI5mt8cyE/MDGgx9X5GtyiKAJXOi7l9CiEJyJ6FKfGwAJZOKawOkumKjfcEm2AnFViyFbPC34TrTSM/opTXgiXA3GfuDBE1mr7QuB/rZrfcFkC6enwwbfQMjDVHPuzlYFgdFqR3PolHijkllnrUVk6JBObLAB6qN86LGUOnvOaOXLBeH51wnwAE5nuWu1L3tC/gL3eut6ilV2eZScmIR1OaWp4=
